# Generated by Django 6.0.4 on 2026-04-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscriber_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='joined_date',
            new_name='subscribed_at',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, help_text='Designates whether the user can publish to the feed.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
